# Dataset description

# General options
# data_path: "../XP_holography/CORPUS/"

# training parameters
model:
  batch_size: 64
  num_epochs: 2
  D: 4
  C: 64
  lr: 0.001
  input_dir:  "./PyTorchCheckpoint/" #"./PyTorchCheckpoint/experiment_2022_03_01-10:00:35/" # directory of saved checkpoints for denoising operation or retraining
  output_dir: null # directory of saved checkpoints for denoising operation or retraining
  start_epoch: null #'epoch\'s number from which we going to retrain'
  freq_save: 1
  perform_validation: True
  graph: True


# Training set
train:
  path: "../XP_holography/CORPUS/DATABASE/" #"../XP_holography/" #
  csv: "holodeep_mat.csv"
  extension: "mat"
  matlab_key_noisy: "NoisyPhase"
  matlab_key_clean: "Phase"
  # image_size: (1024, 1024)

  patch:
    nb_patch_per_image: 2
    size: 50
    stride: 50
    step: 0

  #"add45,transpose,cossin,flip,rot90,rot180,rot270"
  augmentation: "" #add45,add45transpose,cossin,flip,rot90"

eval:
  path: "../XP_holography/" #"../XP_holography/" #
  csv: "holodeep_tiff.csv"
  extension: "tif"
  matlab_key_noisy: ""
  matlab_key_clean: ""
  # image_size: (1024, 1024)
  nb_iteration: 1

# Test set
test:
  path: "../XP_holography/"
  csv: "holodeep_test.csv"
  extension: "tiff"
  matlab_key_noisy: "NoisyPhase"
  matlab_key_clean: "Phase"
  nb_iteration: 3
  save_test_dir: "./TestImages/" # directory of saved test images after denoising operation

